### ISSUE TITLE
桌面端应用不会存储登录状态

### ISSUE THREAD

**Issue by liuyuanjun520** [zmh-program/chatnio#121]
![image](https://github.com/Deeptrain-Community/chatnio/assets/54762364/aaaab28b-dad4-4189-96ad-4d110a377e36)

**Comment by zmh-program** [comment]
请表述清楚

**Comment by zmh-program** [comment]
哦 我知道了

**Comment by liuyuanjun520** [comment]
> 你的意思是tauri桌面端每次开启都不会存储登录？

对的对的，是这个意思
