### ISSUE TITLE
对接部分中转 Anthropic 渠道的格式兼容性问题

### ISSUE THREAD

**Issue by bmwa0813** [zmh-program/chatnio#227]
目前“重新回答”会在现有回答的基础上生成一条新的回复，在使用claude模型时继续对话，会提示found multiple "assistant" roles in a row。

能否改变生成逻辑，用新回复替换原有回答

**Comment by zmh-program** [comment]
fixed. bug created at 2024/7/17 (https://github.com/Deeptrain-Community/chatnio-pro/commit/32979fb45ff68045f14b4a740c42d02d30d2d997).

**Comment by bmwa0813** [comment]
上游是通过openai格式调用的claude，也是目前应用最广泛的方法了，毕竟中转用的都是oneapi此类项目。lobechat等很多前端项目调用同样的api不会出现此情况，不知他们是如何解决的，chatnio无法实现吗？

**Comment by bmwa0813** [comment]
能否判断并仅对OpenAI格式的Claude模型的回答进行处理，使其成为可被Claude模型接纳的格式。

ps：在这里交流一下对本项目的一些看法
作为商业版用户，选择本项目最核心原因是它可以为c端用户提供其他项目所不具备的功能，例如同时支持按次/量付费以及api。至于后台的渠道管理，只需要能保证各类模型可对接oneapi类项目即可。

但目前项目后台渠道管理页面是与oneapi类项目看齐的，需要根据不同厂商模型单独配置渠道，不能无脑对接oneapi，否则使用效果不理想（例如Claude、mj）。这对作为面向c端用户的项目来说，运营成本太高了。（即便是中转商也不能保证每个模型都使用的自建渠道，而非对接的经oneapi转发的上游）

本项目定义为“下一代 AI 一站式 B/C 端解决方案”，但目前提供api中转服务的oneapi类项目生态已很完善，中转供应商人手一个。因此建议，开发重点优先放到C端功能完善，以及对oneapi类项目的适配上。

由衷希望项目越做越好😘 @zmh-program

**Comment by zmh-program** [comment]
这其实是 One API 的设计不完善，并且 One 二开的开源的 New API 修复了此漏洞。如果 Chat Nio 考虑插手的话，因为 One API 是以 OpenAI 格式接入的，如果 chatnio 对 openai 格式进行处理，那么所有 openai 格式的渠道都会应用此规则，原本不是 claude 也会变成 claude 的 prompt 格式，或者有什么好的建议？

**Comment by zmh-program** [comment]
因为 chatnio 不知道上游 one api 他接入的是不是 anthropic 渠道类型变成的 openai 格式，只能知道这只是一个 openai 类型的渠道。

**Comment by bmwa0813** [comment]
你没有好办法我就更不懂了，我只需要提问题，你要考虑的就多了，哈哈哈

**Comment by zmh-program** [comment]
或者 我可以在openai类型的渠道里加个【应用 Anthropic 中转格式兼容】
开启后所有带 `claude`的模型都会pre-format

**Comment by bmwa0813** [comment]
可以解决问题就行诶

**Comment by zmh-program** [comment]
同样也可以参考一下 #232 的方案，将上游换成one hub/new api/shell api, 现在只有one api有这个bug

**Comment by AnnaStreeter** [comment]
此为上游问题，可以加钱对您特殊的上游渠道做单独处理。
