### ISSUE TITLE
MORE LANGUAGUE

### ISSUE THREAD

**Issue by Cristofer543** [zmh-program/chatnio#232]
[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整浏览项目 README 和项目文档并未找到解决方案
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [ ] 我将以礼貌和尊重的态度提问，不得使用不文明用语 (包括在此发布评论的所有人同样适用, 不遵守的人将被 block)
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**

**相关截图 (如果有)**

**Comment by zmh-program** [comment]
which?
