### ISSUE TITLE
请求添加Casdoor单点登录方式

### ISSUE THREAD

**Issue by nebstudio** [zmh-program/chatnio#233]
[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整浏览项目 README 和项目文档并未找到解决方案
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我将以礼貌和尊重的态度提问，不得使用不文明用语 (包括在此发布评论的所有人同样适用, 不遵守的人将被 block)
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
希望商业版增加 [Casdoor](https://github.com/casdoor/casdoor) 这种的单点登录方式：[https://github.com/casdoor/casdoor](https://github.com/casdoor/casdoor)，方便企业统一认证使用。
**相关截图 (如果有)**

**Comment by zmh-program** [comment]
看了一下， Casdoor 是类似于 OAuth 里再套 OAuth? 相当于搭建的 casdoor 平台本身就是一个 oauth? 那这样的话我没法 integrate

**Comment by nebstudio** [comment]
> 看了一下， Casdoor 是类似于本身就有一套账号管理系统 (加mysql之类的)？那这样的话我没法 integrate 呀

是的，他本身是有账号管理的（方便企业统一管理账户信息），但是可以通过SSO 或者 OIDC 进行链接，以三方登录的方式实现（类似于微信登录）：
**参考：**

1. [https://casdoor.org/zh/docs/how-to-connect/oidc-client](https://casdoor.org/zh/docs/how-to-connect/oidc-client)
2. [https://casdoor.org/zh/docs/how-to-connect/single-sign-on](https://casdoor.org/zh/docs/how-to-connect/single-sign-on)

**Comment by zmh-program** [comment]
测了一下不太好，还是直接写provider吧
