### ISSUE TITLE
渠道额度消耗统计

### ISSUE THREAD

**Issue by bmwa0813** [zmh-program/chatnio#235]
[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整浏览项目 README 和项目文档并未找到解决方案
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我将以礼貌和尊重的态度提问，不得使用不文明用语 (包括在此发布评论的所有人同样适用, 不遵守的人将被 block)
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
渠道设置页面增加额度消耗统计，可以的话具体到每个渠道内的单个密钥的额度消耗。（初衷是为了方便掌握官key的额度剩余情况，所以单位似乎用美元合适？如果能做到可以获得oneapi类中转key的剩余额度也很实用）

后台的使用记录中，显示调用的渠道/密钥编号（用户界面不显示）
**相关截图 (如果有)**

**Comment by AnnaStreeter** [comment]
因为架构设计无法测量精准额度，并且openai，azure后台都有自己的dashboard
