### ISSUE TITLE
希望添加预设自定义预设模型功能

### ISSUE THREAD

**Issue by SNESNya** [zmh-program/chatnio#236]
[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整浏览项目 README 和项目文档并未找到解决方案
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我将以礼貌和尊重的态度提问，不得使用不文明用语 (包括在此发布评论的所有人同样适用, 不遵守的人将被 block)
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**

## 希望
预设功能里，可以选择该预设的使用模型。选择模型后，使用该预设就能自动切换模型。

**相关截图 (如果有)**

**Comment by AnnaStreeter** [comment]
修改 prompt.ts 的代码即可实现

**Comment by AnnaStreeter** [comment]
修改 prompt.ts 的代码即可实现
