### ISSUE TITLE
订阅相关

### ISSUE THREAD

**Issue by bmwa0813** [zmh-program/chatnio#239]
[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整浏览项目 README 和项目文档并未找到解决方案
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [ ] 我将以礼貌和尊重的态度提问，不得使用不文明用语 (包括在此发布评论的所有人同样适用, 不遵守的人将被 block)
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
1、支持自定义设定订阅天数。

2、同等级订阅套餐内容发生变动后，现有已订阅该等级套餐的用户会同步获得最新套餐内容。能否已订阅用户仍按原订阅内容，因为新套餐价格与成本可能会与之前不同。

3、开启订阅功能后，即便未添加专业版订阅内容，订阅界面仍会显示专业版。能否当某一版套餐内容为空时，订阅界面不予显示。
**相关截图 (如果有)**

**Comment by AnnaStreeter** [comment]
没有打算，可以定制或者自己改源码
