### ISSUE TITLE
[FEAT]查看历史对话所使用的 model 名称

### ISSUE THREAD

**Issue by superen7527** [zmh-program/chatnio#240]
对话切换模型对话后，查看历史对话，没办法看到历史对话用的哪个模型，不知道能不能优化一下。

另外有一个bug，直接进入或者刷新`/admin/system`界面 会提示 `{"code":1001,"message":"登陆失效～"}`。而返回主页是登录状态。好像是只能从主页进入才会携带token。应该是bug吧？

项目很不错，已商业支持。

**Comment by zmh-program** [comment]
{"code":1001,"message":"登陆失效～"}
这个报错信息不是我们项目的呀

**Comment by zmh-program** [comment]
截图

**Comment by zmh-program** [comment]
这个我完全可以确定不是这里的报错

**Comment by zmh-program** [comment]
你看看你的nginx 反代或者waf什么的有没有什么问题
