### ISSUE TITLE
请求加一个测试模型是否正常连接的功能

### ISSUE THREAD

**Issue by 3377** [zmh-program/chatnio#243]
[//]: # (方框内删除已有的空格，填 x 号)
+ [X ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整浏览项目 README 和项目文档并未找到解决方案
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [ ] 我将以礼貌和尊重的态度提问，不得使用不文明用语 (包括在此发布评论的所有人同样适用, 不遵守的人将被 block)
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
类似new-api里面，填入过后可以测一下是否可以正常连接。
**相关截图 (如果有)**

**Comment by 3377** [comment]
当初测试了3个流行的中转，就因为这个舍弃了。

**Comment by AnnaStreeter** [comment]
直接在聊天栏里输入就行，中转项目没有聊天功能因此才需要测试。
