### ISSUE TITLE
在 `/app/dist/icons` 下添加图标后，界面中仍然没有显示新图标

### ISSUE THREAD

**Issue by piwawa** [zmh-program/chatnio#247]
![image](https://github.com/user-attachments/assets/d4f6dc95-bda5-46dc-83bf-63fefc170cce)

![image](https://github.com/user-attachments/assets/4f006e34-7eef-49ce-86af-0c12dc756c64)

已经重启几次容器，还是这样

**Comment by XiaomaiTX** [comment]
@piwawa  你好！

/app/dist 目录是输出目录
请将你的 icon 放置在/app/public 目录

如果没有问题将关闭此 Issue

Best Regard!
