### ISSUE TITLE
最新模型 o1 不支持流式，请求自动适配非流输出

### ISSUE THREAD

**Issue by piwawa** [zmh-program/chatnio#248]
Unsupported value: 'stream' does not support true with this model. Only the default (false) value is supported. (type: chatnio_upstream_error)

![image](https://github.com/user-attachments/assets/b86df314-5fc1-4a63-8a16-c89cbe864650)

**Comment by SHLE1** [comment]
请求适配`tempreture`固定为1等特性，而且以OpenAI渠道添加会出现`no response`，在其他客户端测试正常。
感谢开发者～

**Comment by AnnaStreeter** [comment]
但是有些o1渠道是支持stream的，强制调整参数不明智，最好方案是根据自己的情况进行调整/修改代码。
