### ISSUE TITLE
文件解析上传无法生成url

### ISSUE THREAD

**Issue by bmwa0813** [zmh-program/chatnio#251]
[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整浏览项目 README 和项目文档并未找到解决方案
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我将以礼貌和尊重的态度提问，不得使用不文明用语 (包括在此发布评论的所有人同样适用, 不遵守的人将被 block)
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
部署了blob文件解析服务，无论模型是否选择为逆向，上传的pdf文件仅能将其中的图片转为url，无法将整个文件转为url。请问可能是哪里配置出问题了吗？
**复现步骤**

**预期结果**

**日志信息**

**相关截图 (如果有)**

**Comment by bmwa0813** [comment]
另外如果直接在部署的blob服务中选择save all上传，是可以生成url的

**Comment by AnnaStreeter** [comment]
说明没支持
