### ISSUE TITLE
开源版很久没更新了，商业版的购买链接也都失效了

### ISSUE THREAD

**Issue by Pevernow** [zmh-program/chatnio#252]

**Comment by Pevernow** [comment]
nio官网是4.11，开源版只到3.11

**Comment by Pevernow** [comment]
https://www.chatnio.com/pro 404

**Comment by zmh-program** [comment]
是从哪看到的商业版购买链接？现在已经在这里了

https://www.chatnio.com/docs/contact#授权价格
