### ISSUE TITLE
希望更新开源版本

### ISSUE THREAD

**Issue by zzc0208** [zmh-program/chatnio#254]
[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整浏览项目 README 和项目文档并未找到解决方案
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我将以礼貌和尊重的态度提问，不得使用不文明用语 (包括在此发布评论的所有人同样适用, 不遵守的人将被 block)
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
作者您好，开源版本的chatnio目前版本是3.11.1，但是我注意到官网的闭源版本已经更新到4.13.0，因此想了解一下您是否有计划继续更新开源版本。我们非常期待能继续使用最新的开源版本，并对您的开发工作表示由衷的感谢。

**相关截图 (如果有)**

**Comment by zzc0208** [comment]
V4版本的界面相比V3有了很大的提升，并且新增了用户后台等实用功能。如果能够更新开源版本，我相信会有更多用户了解到V4的改进，从而提升他们的购买意愿。与此同时，开源社区也能为V4版本的插件市场贡献更多的插件，进一步丰富整个生态系统。

再次感谢您的付出！

**Comment by AnnaStreeter** [comment]
本项目leader已经去写新的项目了，这段时间由我负责后续开发之类的事情，目前在我们正在考虑收购事项，需要等一段时间后再根据意向落实下一步规划。

**Comment by zzc0208** [comment]
了解了，感谢，我们也非常期待这次收购的顺利完成以及未来的开源计划。我们会持续关注此issue，并期待看到更多关于项目发展的动态。

**Comment by zmh-program** [comment]
👋 hi, @zzc0208!

> 在经过一段时间的沉淀与积累后，CoAI.Dev (原 ChatNio) 即将焕新启程，新产品即将在不久的未来推出！
欢迎大家前往新 Discord 社区，一起期待新版本的到来！

> CoAI.dev 致力于打造一个专注于前沿 AI Startup、企业 LLM 解决方案。在这里, 欢迎你与来自世界各地的 AI 研究者、开发者、创业者和爱好者分享见解, 探讨前沿技术, 共同学习成长。
我们的社群管理团队会不定期分享与组织 AMA、技术分享会、AI 黑客松等活动, 为成员提供交流互动的机会。让 CoAI.dev 成为一个充满活力与创造力的社区。

> Discord：https://discord.gg/rpzNSmqaF2
