### ISSUE TITLE
网页项目崩溃

### ISSUE THREAD

**Issue by nothing0here** [zmh-program/chatnio#259]
[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整浏览项目 README 和项目文档并未找到解决方案
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我将以礼貌和尊重的态度提问，不得使用不文明用语 (包括在此发布评论的所有人同样适用, 不遵守的人将被 block)
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
Windows 11 24h2 with Microsoft Edge 版本 130.0.2849.68 (正式版本) (64 位) 访问 Chatnio.net，通过Deeptrain/Github账号登陆使用预设问题进行Chat后页面崩溃。
**复现步骤**
如上
**预期结果**
期望可以正常使用

**日志信息**
[error-1730799097542.log](https://github.com/user-attachments/files/17630223/error-1730799097542.log)
**相关截图 (如果有)**
![image](https://github.com/user-attachments/assets/28239109-e80c-4ed8-a201-3d0b9fb2f296)

**Comment by jerviscui** [comment]
这项目开始编小作文博流量了是吧？

**Comment by ZZQ987** [comment]
我也遇到了，，，
