### ISSUE TITLE
An error about API requests

### ISSUE THREAD

**Issue by ZZQ987** [zmh-program/chatnio#260]
[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整浏览项目 README 和项目文档并未找到解决方案
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我将以礼貌和尊重的态度提问，不得使用不文明用语 (包括在此发布评论的所有人同样适用, 不遵守的人将被 block)
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
我通过request请求调用API，chatnio.net网站可以收到，流水min]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整浏览项目 README 和项目文档并未找到解决方案
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [ ] 我将以礼貌和尊重的态度提问，不得使用不文明用语 (包括在此发布评论的所有人同样适用, 不遵守的人将被 block)
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
我通过request请求调用API，chatnio.net网站可以收到，日志里面可以看到模型做出了回复，但是给我返回的一直是502 error
**复现步骤**

代码如下：

```
import requests

url = 'https://api.chatnio.net/v1/chat/completions'
api_key = '。。。。。。。'


headers = {
    'Authorization': f'Bearer {api_key}',
    'Content-Type': 'application/json'
}

data = {
    'model': 'gpt-4',
    'messages': [
        {'role':'user','content':'。。。。。'}
    ]
}

response = requests.post(url, headers=headers, json=data)
content = response.json().get('choices')[0].get('message').get('content')

print(content)

```
**预期结果**

**日志信息**

**相关截图 (如果有)**

![image](https://github.com/user-attachments/assets/616437bd-8655-4911-9c78-4fdb6aa31390)

**Comment by zmh-program** [comment]
502 是由于访问量激增导致部分节点可能会出现异常，我们的运维正在加固WAF以减少此类情况发生！
