### ISSUE TITLE
支持tts和whisper

### ISSUE THREAD

**Issue by acte9548224** [zmh-program/chatnio#74]
像lobechat那样随时可以转语音

**Comment by TenLun** [comment]
输入法自带的不香吗？

**Comment by zmh-program** [comment]
我不好说怎么写计费，总不可能在 whisper 下面显示消耗点数？那用户的直觉就是 不敢多说一秒直接关闭了。

付费的 whisper 总感觉直接不如免费的系统自带的 stt 语音转文字

tts 可以保留，但是 openai 的 tts 的中文的确是有点...

**Comment by zmh-program** [comment]
先保留，标个 feature
